apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    io.kompose.service: flask
  name: flask
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  - name: "9200"
    port: 9200
    targetPort: 9200
  selector:
    io.kompose.service: flask
  type: LoadBalancer
