apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: kafka
  name: kafka
spec:
  clusterIP: None
  ports:
  - name: "kafka-port"
    port: 9092
    protocol: TCP
    targetPort: 9092
  selector:
    io.kompose.service: kafka
#spec:
#  ports:
#  - name: "9092"
#    port: 9092
#    targetPort: 9092
#  selector:
#    io.kompose.service: kafka
#  type: LoadBalancer
