apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -v
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo-seed
  name: mongo-seed
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo-seed
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -v
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/red1: "true"
        io.kompose.service: mongo-seed
    spec:
      containers:
      - args:
        - mongoimport --host mongo --port 27017 -d agile_data_science -c origin_dest_distances
          --mode upsert --type json --file /origin_dest_distances.jsonl
        env:
        - name: MONGO_HOST
          value: mongo
        - name: MONGO_PORT
          value: "27017"
        image: jlmendo11/mongo_seed
        imagePullPolicy: ""
        name: mongo-seed
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
