apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -v
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: spark-web
  name: spark-service-web
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: spark-master
  type: LoadBalancer
