version: "3"

services:

  zookeeper:

    container_name: zookeeper

    image: wurstmeister/zookeeper

    ports:

      - "2181:2181"

    hostname: zookeeper

    networks:

      - red1


  kafka:

    container_name: kafka

    image: wurstmeister/kafka:2.12-2.3.0

    ports:

      - "9092:9092"

    depends_on:

      - zookeeper

    hostname: kafka

    environment:

      # KAFKA_ADVERTISED_HOST_NAME: kafka

      # KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # KAFKA_CREATE_TOPICS: "flight_delay_classification_request:1:1"

      # KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094

      # KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094

      # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT

      # KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE



      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

      KAFKA_LISTENERS: PLAINTEXT://kafka:9092

      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_CREATE_TOPICS: "flight_delay_classification_request:1:1"

    networks:

      - red1

    

  mongo:

    container_name: mongo

    image: mongo:4.4.2

    ports:

      - "27017:27017"

    depends_on:

      - kafka

    hostname: mongo

    networks:

      - red1



  mongo_seed:

    image: jlmendo11/mongo_seed

    container_name: mongo_seed

    depends_on:

      - mongo

    networks:

      - red1

    environment:

      - MONGO_HOST=mongo

      - MONGO_PORT=27017

    command:

      - "mongoimport --host mongo --port 27017 -d agile_data_science -c origin_dest_distances --mode upsert --type json --file /origin_dest_distances.jsonl"

      # - "mongo agile_data_science --eval 'db.origin_dest_distances.ensureIndex({Origin: 1, Dest: 1})'"


  cassandra:

    container_name: cassandra

    image: cassandra:4.1.3
    
    depends_on:
    
      - kafka

    ports:

      - "9042:9042"
  
    hostname: cassandra

    networks:

      - red1 

  
  cassandra_seed:

    container_name: cassandra_seed

    image: cassandra_seed

    depends_on:
    
      - cassandra

    networks:

      - red1 
      
  flask:

    container_name: flask

    image: jlmendo11/flask2

    ports:

      - "5000:5000"

      - "9200:9200"

    depends_on:

      - spark-submit
      
      - cassandra

    hostname: flask

    networks:

      - red1
      
  spark-master:
  
    image: bde2020/spark-master:3.3.0-hadoop3.3
    
    container_name: spark-master
    
    depends_on:
    
      - cassandra_seed
      
    ports:
    
      - "7077:7077"
      
      - "9001:9001"
      
      - "8080:8080"
      
    environment:
    
      - "SPARK_MASTER=spark-master:7077"
      
      - "INIT_DAEMON_STEP=setup_spark"
      
      - "constraint:node==spark-master"
      
  
  spark-worker-1:
  
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    
    container_name: spark-worker-1
    
    depends_on:
    
      - spark-master
      
    ports:
    
      - "8081:8081"
      
    environment:
    
      - "SPARK_MASTER=spark-master:7077"
      
      - "INIT_DAEMON_STEP=setup_spark"
      
      - "constraint:node==spark-worker-1"

      
  spark-worker-2:
  
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    
    container_name: spark-worker-2
    
    depends_on:
    
      - spark-master
      
    ports:
    
      - "8082:8081"
      
    environment:
    
      - "SPARK_MASTER=spark-master:7077"
      
      - "INIT_DAEMON_STEP=setup_spark"
      
      - "constraint:node==spark-worker-2"
 
          

  spark-submit:

    image: spark-submit 
    
    container_name: spark-submit

    ports:

      - "4040:4040"

    depends_on:

      - spark-master

    hostname: spark-submit 
    
    environment:
    
      - "SPARK_MASTER=spark-master:7077"
      
      - "constraint:node==spark-submit"

    networks:

      - red1



networks:

  red1:

    driver : bridge
